# Dockerfile for Celery Beat
FROM python:3.9-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends default-mysql-client && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app /app

CMD ["celery", "-A", "core.celery_app", "beat", "--loglevel=info", "--scheduler=sqlalchemy_celery_beat.schedulers:DatabaseScheduler"]
