services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A core.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      redis: 
        condition: service_started
      db:
        condition: service_healthy

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A core.celery_app beat --loglevel=info
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      redis: 
        condition: service_started
      db:
        condition: service_healthy
      celery_worker:
        condition: service_started
volumes:
  db_data:
