services:
  backend:
    image: pedroaires/cursos-ufcg-backend:latest
    container_name: backend
    environment:
      DATABASE_URL: "mysql+pymysql://root:databridge@db:3306/databridge_schema"
    expose:
      - "5000"
    networks:
      - cursos-ufcg-data-bridge_default

  frontend:
    image: pedroaires/cursos-ufcg-frontend:latest
    container_name: frontend
    environment:
      BACKEND_URL: "/api/"
    expose:
      - "80"
    networks:
      - cursos-ufcg-data-bridge_default

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - cursos-ufcg-data-bridge_default

networks:
  cursos-ufcg-data-bridge_default:
    external: true