# Nomes do campo da API mapeados para o nome do campo do banco de dados
# Mesmo as colunas que nao necessitam ser mapeadas precisam estar presentes no arquivo
# pois as que nao estiverem serao removidas entao se nao quiser mapear uma coluna apenas coloque o mesmo nome no mapeamento
cursos:
  code: codigo_curso
  name: nome_comum
  disponivel: disponivel
  schema: schema
  campus: campus

alunos:
  statusTerm: periodo_situacao
  admissionTerm: periodo_ingressao
  admissionCode: codigo_ingressao
  status: situacao
  inactivityReason: motivo_inatividade
  placeOfBirth: estado
  secondarySchoolType: tipo_ensino
  affirmativePolicy: modalidade_concorrencia
  age: idade
  gender: genero
  codigo_curso: codigo_curso

curriculos:
  courseCode: codigo_curso
  curriculumCode: codigo_curriculo
  minNumberOfTerms: min_periodos
  maxNumberOfTerms: max_periodos
  minNumberOfEnrolledCredits: min_creditos_matriculados
  maxNumberOfEnrolledCredits: max_creditos_matriculados
  minMandatoryCreditsNeeded: min_creditos_obrigatorios
  minOptionalCreditsNeeded: min_creditos_optativos
  minComplementaryCreditsNeeded: min_creditos_complementares
  minAcademicsExtensionActivities: min_atividades_extensao

disciplinas:
  subjectCode: codigo_disciplina
  name: disciplina
  credits: creditos
  hours: horas
  type: tipo 
  idealSemester: semestre
  curriculumCode: codigo_curriculo
  courseCode: codigo_curso

historico:
  subjectCode: codigo_disciplina
  term: periodo 
  grade: media
  status: situacao
  registration: matricula_fake
  codigo_curso: codigo_curso
  codigo_curriculo: codigo_curriculo