# Nomes do campo da API mapeados para o nome do campo do banco de dados
# Mesmo as colunas que nao necessitam ser mapeadas precisam estar presentes no arquivo
# pois as que nao estiverem serao removidas entao se nao quiser mapear uma coluna apenas coloque o mesmo nome no mapeamento
cursos:
  codigo_do_curso: codigo_curso
  descricao: nome_comum
  disponivel: disponivel
  schema: schema
  campus: campus

alunos:
  matricula_do_estudante: matricula
  periodo_de_ingresso: periodo_ingressao
  situacao: situacao
  motivo_de_evasao: motivo_inatividade
  codigo_do_curso: codigo_curso

curriculos:
  codigo_do_curso: codigo_curso
  codigo_do_curriculo: codigo_curriculo
  duracao_minima: min_periodos
  duracao_maxima: max_periodos
  minimo_creditos_disciplinas_optativas: min_creditos_optativos
  carga_horaria_minima_total: carga_horaria_minima_total

disciplinas:
  id: id
  codigo_da_disciplina: codigo_disciplina
  nome: disciplina
  quantidade_de_creditos: creditos
  horas_totais: horas
  tipo: tipo
  semestre_ideal: semestre
  codigo_do_curriculo: codigo_curriculo
  codigo_do_curso: codigo_curso

historico:
  codigo_da_disciplina: codigo_disciplina
  periodo: periodo
  media_final: media
  status: situacao
  codigo_do_curriculo: codigo_curriculo
  codigo_do_curso: codigo_curso
  matricula_do_estudante: matricula

prerequisitos:
  disciplina_id: disciplina_id
  prerequisito_id: prerequisito_id
  condicao: condicao
  ordem_prioridade: ordem_prioridade
  tipo: tipo
  operador: operador